import clsx from 'clsx'
import { useEffect, useState } from 'react'
import { IconAlert, IconLock, IconShield, IconSpark } from './icons'
import { Banner, Card, Skeleton, Spinner } from './ui'
import { ApiError, api } from '../lib/api'

interface SentimentBreakdown {
  analysed: number
  average_score: number | null
  distribution: Record<string, number>
  aspects: { aspect: string; count: number }[]
}

interface SummaryPayload {
  headline?: string
  strengths?: string[]
  watch_outs?: string[]
  themes?: string[]
  narrative?: string
}

interface SummaryResponse {
  status: 'ready' | 'suppressed' | 'failed' | 'stale' | 'absent'
  reason?: string
  payload?: SummaryPayload
  source_count?: number
  provider?: string
  model_id?: string
  prompt_version?: string
  generated_at?: string
  is_local_fallback?: boolean
}

interface AiStatus {
  enabled: boolean
  provider: string
  is_local_fallback: boolean
  sentiment_model: string
  summary_model: string
  min_responses_for_summary: number
}

const BANDS: { key: string; label: string; tone: string }[] = [
  { key: 'very_negative', label: 'Very negative', tone: 'bg-critical' },
  { key: 'negative', label: 'Negative', tone: 'bg-critical/60' },
  { key: 'neutral', label: 'Neutral', tone: 'bg-ink-300 dark:bg-ink-600' },
  { key: 'positive', label: 'Positive', tone: 'bg-positive/60' },
  { key: 'very_positive', label: 'Very positive', tone: 'bg-positive' },
]

function SentimentBar({ distribution }: { distribution: Record<string, number> }) {
  const total = Object.values(distribution).reduce((sum, value) => sum + value, 0)
  if (!total) return null
  return (
    <>
      <div className="flex h-2.5 w-full overflow-hidden rounded-full">
        {BANDS.map((band) => {
          const count = distribution[band.key] ?? 0
          if (!count) return null
          return (
            <div
              key={band.key}
              className={band.tone}
              style={{ width: `${(count / total) * 100}%` }}
              title={`${band.label}: ${count}`}
            />
          )
        })}
      </div>
      <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1">
        {BANDS.filter((band) => distribution[band.key]).map((band) => (
          <span
            key={band.key}
            className="flex items-center gap-1.5 text-2xs text-ink-500 dark:text-ink-400"
          >
            <span className={clsx('h-2 w-2 rounded-full', band.tone)} />
            {band.label}
            <span className="tabular font-medium">{distribution[band.key]}</span>
          </span>
        ))}
      </div>
    </>
  )
}

/**
 * The AI panel on a results page.
 *
 * Two things it always does, both deliberate:
 *
 *  - It states which model produced the text, and says plainly when that is
 *    the offline analyser rather than a language model. A summary about a
 *    person is not something to be vague about the provenance of.
 *  - It renders the suppression state as an explanation rather than an empty
 *    box, so the reader understands that nothing was generated rather than
 *    assuming the feature is broken.
 */
export function AiPanel({
  cycleId,
  targetId,
  canGenerate,
}: {
  cycleId: string
  targetId: string
  canGenerate?: boolean
}) {
  const [status, setStatus] = useState<AiStatus | null>(null)
  const [sentiment, setSentiment] = useState<SentimentBreakdown | null>(null)
  const [summary, setSummary] = useState<SummaryResponse | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const load = () => {
    api.get<AiStatus>('/ai/status').then(setStatus).catch(() => {})
    api
      .get<SentimentBreakdown>(`/ai/cycles/${cycleId}/sentiment?target_id=${targetId}`)
      .then(setSentiment)
      .catch(() => setSentiment(null))
    api
      .get<SummaryResponse>(`/ai/cycles/${cycleId}/targets/${targetId}/summary`)
      .then(setSummary)
      .catch(() => setSummary({ status: 'absent' }))
  }

  useEffect(load, [cycleId, targetId])

  const generate = async () => {
    setBusy(true)
    setError(null)
    try {
      await api.post(`/ai/cycles/${cycleId}/analyse`)
      load()
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Analysis failed.')
    } finally {
      setBusy(false)
    }
  }

  if (!summary) {
    return <Skeleton className="h-48 w-full rounded-lg" />
  }

  return (
    <Card
      title={
        <span className="flex items-center gap-2">
          <IconSpark width={16} height={16} className="accent-text" />
          AI analysis
        </span>
      }
      hint={
        status
          ? status.is_local_fallback
            ? 'Generated by the built-in offline analyser — no language model is configured.'
            : `Generated by ${status.summary_model}.`
          : undefined
      }
      action={
        canGenerate && (
          <button
            type="button"
            className="btn-secondary px-2.5 py-1 text-xs"
            disabled={busy}
            onClick={generate}
          >
            {busy && <Spinner />}
            {summary.status === 'ready' ? 'Regenerate' : 'Analyse'}
          </button>
        )
      }
    >
      {error && (
        <Banner tone="error" className="mb-4">
          {error}
        </Banner>
      )}

      {/* Suppression is explained, never rendered as an empty state. */}
      {summary.status === 'suppressed' && (
        <div className="flex items-start gap-2.5 rounded-md border border-ink-200 bg-ink-50 p-4 text-sm dark:border-ink-700 dark:bg-ink-900/60">
          <IconLock width={15} height={15} className="mt-0.5 shrink-0 text-ink-400" />
          <div>
            <p className="font-medium text-ink-800 dark:text-ink-100">
              No summary was generated
            </p>
            <p className="mt-0.5 text-ink-600 dark:text-ink-300">{summary.reason}</p>
            <p className="mt-1.5 text-2xs text-ink-400">
              Nothing was sent for analysis and nothing was stored. A summary of
              too few comments would reproduce them.
            </p>
          </div>
        </div>
      )}

      {summary.status === 'absent' && (
        <p className="text-sm text-ink-500 dark:text-ink-400">
          No analysis has been run for this round yet.
        </p>
      )}

      {summary.status === 'failed' && (
        <Banner tone="warning">
          <span className="flex items-center gap-1.5">
            <IconAlert width={14} height={14} />
            Analysis did not complete. {summary.reason}
          </span>
        </Banner>
      )}

      {summary.status === 'ready' && summary.payload && (
        <>
          <p className="text-base font-medium leading-relaxed text-ink-900 dark:text-ink-50">
            {summary.payload.headline}
          </p>

          {summary.payload.narrative && (
            <p className="mt-2.5 text-sm leading-relaxed text-ink-600 dark:text-ink-300">
              {summary.payload.narrative}
            </p>
          )}

          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            {(summary.payload.strengths ?? []).length > 0 && (
              <div>
                <p className="label-caps mb-1.5">Consistently praised</p>
                <ul className="space-y-1.5">
                  {summary.payload.strengths?.map((item) => (
                    <li
                      key={item}
                      className="border-l-2 border-positive pl-2.5 text-sm text-ink-700 dark:text-ink-200"
                    >
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {(summary.payload.watch_outs ?? []).length > 0 && (
              <div>
                <p className="label-caps mb-1.5">Raised more than once</p>
                <ul className="space-y-1.5">
                  {summary.payload.watch_outs?.map((item) => (
                    <li
                      key={item}
                      className="border-l-2 border-caution pl-2.5 text-sm text-ink-700 dark:text-ink-200"
                    >
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          {(summary.payload.themes ?? []).length > 0 && (
            <div className="mt-4 flex flex-wrap gap-1.5">
              {summary.payload.themes?.map((theme) => (
                <span
                  key={theme}
                  className="chip bg-ink-100 text-ink-600 dark:bg-ink-800 dark:text-ink-300"
                >
                  {theme}
                </span>
              ))}
            </div>
          )}

          {/* Provenance, always. */}
          <p className="mt-4 flex flex-wrap items-center gap-x-2 border-t border-ink-200 pt-3 text-2xs text-ink-400 dark:border-ink-800">
            <IconShield width={11} height={11} />
            Built from {summary.source_count} response
            {summary.source_count === 1 ? '' : 's'} by{' '}
            <span className="font-mono">{summary.model_id}</span>
            {summary.generated_at && (
              <>· {new Date(summary.generated_at).toLocaleDateString()}</>
            )}
            {summary.is_local_fallback && (
              <span className="chip bg-caution/12 text-caution">Offline analyser</span>
            )}
          </p>
        </>
      )}

      {sentiment && sentiment.analysed > 0 && (
        <div className="mt-5 border-t border-ink-200 pt-4 dark:border-ink-800">
          <div className="mb-2 flex items-baseline justify-between gap-3">
            <p className="label-caps">Sentiment across {sentiment.analysed} comments</p>
            {sentiment.average_score !== null && (
              <span
                className={clsx(
                  'tabular text-sm font-semibold',
                  sentiment.average_score > 0.15 && 'text-positive',
                  sentiment.average_score < -0.15 && 'text-critical',
                  Math.abs(sentiment.average_score) <= 0.15 && 'text-ink-500',
                )}
              >
                {sentiment.average_score > 0 ? '+' : ''}
                {sentiment.average_score.toFixed(2)}
              </span>
            )}
          </div>
          <SentimentBar distribution={sentiment.distribution} />

          {sentiment.aspects.length > 0 && (
            <div className="mt-3">
              <p className="label-caps mb-1.5">Most discussed</p>
              <div className="flex flex-wrap gap-1.5">
                {sentiment.aspects.map((aspect) => (
                  <span
                    key={aspect.aspect}
                    className="chip accent-soft-bg accent-text"
                  >
                    {aspect.aspect}
                    <span className="tabular ml-1 opacity-70">{aspect.count}</span>
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </Card>
  )
}
