"""Export renderers: CSV, Excel, and branded PDF.

All three consume the same `ReportDefinition` and the same already-fetched
rows, so they cannot disagree with each other or with the screen.
"""

from __future__ import annotations

import csv
import io
from collections.abc import Iterator
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import xlsxwriter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.core.config import settings
from app.reporting.registry import Column, ReportDefinition
from app.schemas.common import ResolvedWindow

# Brand palette, kept in sync with the frontend design tokens.
INK = colors.HexColor("#12161C")
SLATE = colors.HexColor("#5A6472")
HAIRLINE = colors.HexColor("#DDE1E6")
ZEBRA = colors.HexColor("#F6F7F9")


class ExportContext:
    """Everything a renderer needs beyond the rows themselves."""

    def __init__(
        self,
        *,
        report: ReportDefinition,
        window: ResolvedWindow,
        filter_summary: list[tuple[str, str]],
        org_name: str,
        org_timezone: str,
        accent_color: str = "#B4633A",
        logo_path: Path | None = None,
        generated_by: str = "",
    ) -> None:
        self.report = report
        self.window = window
        self.filter_summary = filter_summary
        self.org_name = org_name
        self.org_timezone = org_timezone
        self.accent_color = accent_color
        self.logo_path = logo_path
        self.generated_by = generated_by
        self.generated_at = datetime.now(ZoneInfo(org_timezone or "UTC"))

    @property
    def filename_stem(self) -> str:
        stamp = self.generated_at.strftime("%Y%m%d-%H%M")
        safe_org = "".join(
            char if char.isalnum() else "-" for char in self.org_name.lower()
        ).strip("-")
        return f"{safe_org}-{self.report.key}-{stamp}"


def _format_cell(value: Any, column: Column, tz: ZoneInfo) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        local = value.astimezone(tz) if value.tzinfo else value
        return local.strftime("%Y-%m-%d %H:%M")
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, Decimal):
        return f"{value:,.2f}"
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value)
    if isinstance(value, dict):
        return "; ".join(f"{k}={v}" for k, v in value.items())
    return str(value)


# --- CSV --------------------------------------------------------------------

def _csv_safe(text: str) -> str:
    """Neutralise spreadsheet formula injection.

    A cell beginning =, +, -, or @ is executed as a formula by Excel and
    Sheets. Free-text feedback is attacker-controllable, so any of it that
    reaches a CSV is a code execution vector against whoever opens the file.
    Prefixing a single quote makes it inert and still readable.
    """
    if text and text[0] in ("=", "+", "-", "@", "\t", "\r"):
        return "'" + text
    return text


def render_csv(context: ExportContext, rows: list[dict[str, Any]]) -> Iterator[str]:
    """Stream a CSV so a large export never has to fit in memory."""
    tz = ZoneInfo(context.org_timezone or "UTC")
    columns = context.report.export_columns("csv")
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")

    def flush() -> str:
        value = buffer.getvalue()
        buffer.seek(0)
        buffer.truncate(0)
        return value

    # Provenance header. Without it an exported file is unattributable.
    writer.writerow([f"{settings.product_name} - {context.report.title}"])
    writer.writerow(["Organization", context.org_name])
    for label, value in context.filter_summary:
        writer.writerow([label, value])
    writer.writerow(
        ["Generated", context.generated_at.strftime("%Y-%m-%d %H:%M %Z")]
    )
    writer.writerow(["Generated by", context.generated_by])
    writer.writerow([])
    yield flush()

    writer.writerow([column.label for column in columns])
    yield flush()

    for row in rows:
        writer.writerow(
            [_csv_safe(_format_cell(row.get(c.key), c, tz)) for c in columns]
        )
        yield flush()


# --- Excel ------------------------------------------------------------------

def render_xlsx(context: ExportContext, rows: list[dict[str, Any]]) -> bytes:
    tz = ZoneInfo(context.org_timezone or "UTC")
    columns = context.report.export_columns("xlsx")

    stream = io.BytesIO()
    workbook = xlsxwriter.Workbook(
        stream, {"in_memory": True, "constant_memory": True, "default_date_format": "yyyy-mm-dd"}
    )

    title_fmt = workbook.add_format(
        {"bold": True, "font_size": 15, "font_color": "#12161C"}
    )
    meta_label = workbook.add_format({"bold": True, "font_color": "#5A6472"})
    meta_value = workbook.add_format({"font_color": "#12161C"})
    header_fmt = workbook.add_format(
        {
            "bold": True,
            "bg_color": context.accent_color,
            "font_color": "#FFFFFF",
            "border": 1,
            "border_color": "#FFFFFF",
            "align": "left",
            "valign": "vcenter",
            "text_wrap": True,
        }
    )
    cell_fmt = workbook.add_format({"valign": "top", "text_wrap": False})
    number_fmt = workbook.add_format({"valign": "top", "num_format": "#,##0"})

    sheet = workbook.add_worksheet(context.report.title[:31] or "Report")

    sheet.write(0, 0, f"{settings.product_name} - {context.report.title}", title_fmt)
    row_cursor = 2
    meta: list[tuple[str, str]] = [("Organization", context.org_name)]
    meta += context.filter_summary
    meta += [
        ("Generated", context.generated_at.strftime("%Y-%m-%d %H:%M %Z")),
        ("Generated by", context.generated_by),
        ("Rows", str(len(rows))),
    ]
    for label, value in meta:
        sheet.write(row_cursor, 0, label, meta_label)
        sheet.write(row_cursor, 1, value, meta_value)
        row_cursor += 1

    header_row = row_cursor + 1
    for index, column in enumerate(columns):
        sheet.write(header_row, index, column.label, header_fmt)
        sheet.set_column(index, index, min(max(column.width, 10), 60))

    for offset, row in enumerate(rows, start=1):
        for index, column in enumerate(columns):
            value = row.get(column.key)
            if column.kind == "number" and isinstance(value, (int, float, Decimal)):
                sheet.write_number(header_row + offset, index, float(value), number_fmt)
            else:
                sheet.write_string(
                    header_row + offset,
                    index,
                    _format_cell(value, column, tz),
                    cell_fmt,
                )

    sheet.freeze_panes(header_row + 1, 0)
    if rows:
        sheet.autofilter(header_row, 0, header_row + len(rows), len(columns) - 1)

    workbook.close()
    return stream.getvalue()


# --- PDF --------------------------------------------------------------------

def _pdf_styles(accent: str) -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "FacetTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=17,
            leading=21,
            alignment=0,
            textColor=INK,
            spaceAfter=2,
        ),
        "subtitle": ParagraphStyle(
            "FacetSubtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=SLATE,
        ),
        "cell": ParagraphStyle(
            "FacetCell",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=INK,
        ),
        "head": ParagraphStyle(
            "FacetHead",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10.5,
            textColor=colors.white,
        ),
        "accent": ParagraphStyle(
            "FacetAccent",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.HexColor(accent),
        ),
    }


def render_pdf(context: ExportContext, rows: list[dict[str, Any]]) -> bytes:
    tz = ZoneInfo(context.org_timezone or "UTC")
    columns = context.report.export_columns("pdf")
    styles = _pdf_styles(context.accent_color)
    accent = colors.HexColor(context.accent_color)

    stream = io.BytesIO()
    page_size = landscape(A4) if len(columns) > 5 else A4
    doc = SimpleDocTemplate(
        stream,
        pagesize=page_size,
        leftMargin=14 * mm,
        rightMargin=14 * mm,
        topMargin=14 * mm,
        bottomMargin=16 * mm,
        title=f"{context.report.title} - {context.org_name}",
        author=settings.product_name,
    )

    story: list[Any] = []

    # Branded header: the tenant's own logo, not ours. A white-labelled report
    # that carries the vendor's mark instead of the customer's is not
    # white-labelled.
    header_cells: list[Any] = []
    if context.logo_path and context.logo_path.exists():
        try:
            logo = Image(str(context.logo_path))
            ratio = logo.imageHeight / float(logo.imageWidth or 1)
            logo.drawWidth = 34 * mm
            logo.drawHeight = min(34 * mm * ratio, 16 * mm)
            logo.hAlign = "LEFT"
            header_cells.append(logo)
        except Exception:  # noqa: BLE001 - a bad logo must not break the report
            header_cells.append(Paragraph(context.org_name, styles["subtitle"]))
    else:
        header_cells.append(Paragraph(f"<b>{context.org_name}</b>", styles["subtitle"]))

    header_cells.append(
        Paragraph(
            f"{context.generated_at.strftime('%d %b %Y, %H:%M %Z')}<br/>"
            f"{context.generated_by}",
            ParagraphStyle("right", parent=styles["subtitle"], alignment=2),
        )
    )
    header = Table([header_cells], colWidths=[doc.width * 0.6, doc.width * 0.4])
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LINEBELOW", (0, 0), (-1, 0), 1.4, accent),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ]
        )
    )
    story += [header, Spacer(1, 9)]

    story.append(Paragraph(context.report.title, styles["title"]))
    story.append(Paragraph(context.report.description, styles["subtitle"]))
    story.append(Spacer(1, 7))

    summary_bits = " &nbsp;•&nbsp; ".join(
        f"<b>{label}:</b> {value}" for label, value in context.filter_summary
    )
    story.append(
        Paragraph(
            f"{summary_bits} &nbsp;•&nbsp; <b>Rows:</b> {len(rows):,}", styles["subtitle"]
        )
    )
    story.append(Spacer(1, 10))

    if not rows:
        story.append(Paragraph("No records matched these filters.", styles["cell"]))
    else:
        weights = [max(column.width, 8) for column in columns]
        total_weight = sum(weights) or 1
        col_widths = [doc.width * (w / total_weight) for w in weights]

        table_data: list[list[Any]] = [
            [Paragraph(column.label, styles["head"]) for column in columns]
        ]
        for row in rows:
            table_data.append(
                [
                    Paragraph(
                        _format_cell(row.get(column.key), column, tz).replace("&", "&amp;")
                        .replace("<", "&lt;"),
                        styles["cell"],
                    )
                    for column in columns
                ]
            )

        table = Table(table_data, colWidths=col_widths, repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), accent),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("LINEBELOW", (0, 0), (-1, -1), 0.4, HAIRLINE),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
        ]
        table.setStyle(TableStyle(style))
        story.append(table)

    def _decorate(canvas, document) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(SLATE)
        canvas.drawString(
            document.leftMargin,
            10 * mm,
            f"{context.org_name} • {context.report.title} • Confidential",
        )
        canvas.drawRightString(
            document.pagesize[0] - document.rightMargin,
            10 * mm,
            f"Page {canvas.getPageNumber()}",
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=_decorate, onLaterPages=_decorate)
    return stream.getvalue()


MEDIA_TYPES = {
    "csv": "text/csv; charset=utf-8",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pdf": "application/pdf",
}
